client_config_backend: file
client_config:
      client_id: 819613419160-ltvq6voi9eorhabuaen8otpc9uhq005s.apps.googleusercontent.com
      client_secret: secret

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_new_token: True

oauth_scope:
    - https://www.googleapis.com/auth/drive